### ISSUE TITLE
Need a Video

### ISSUE THREAD

**Issue by Sandeepxp** [th3unkn0n/TeleGram-Scraper#1]
We Need Video For Help !!
Please Make a video and upload it ! 
Thanks 
+ Need Your Insta Handle

**Comment by th3unkn0n** [comment]
Ok I will

**Comment by keyiflerolsun** [comment]
> https://youtu.be/I8oR9tuYyrU

**Comment by keyiflerolsun** [comment]
> We Need Video For Help !!
> Please Make a video and upload it !
> Thanks
> 
> * Need Your Insta Handle

https://youtu.be/I8oR9tuYyrU
