### ISSUE TITLE
The scraper can't paste more than 50 members why???

### ISSUE THREAD

**Issue by Mrnvdp07** [th3unkn0n/TeleGram-Scraper#10]

**Comment by th3unkn0n** [comment]
Paste what , there is nothing for paste

**Comment by VASPLab** [comment]
Hey dude,
Really appreciate it.... 
Here is an issue.... after sending a message to 10 users I am getting this error
![Screenshot_2020-01-28-00-24-36-715_com termux](https://user-images.githubusercontent.com/24790429/73204217-988af500-4164-11ea-808b-62d44931156b.jpg)
Please look at this and let us know...and again thank you & keep doing such great work. 👏

**Comment by Mrnvdp07** [comment]
Comes peer flood error when add member in our group . There is only 50 member add from your adder ...
Peer flood error because of telegram API .
Can any solution to add more than 1k member in group

**Comment by Mrnvdp07** [comment]
Bro 
Tell me about telegram cli and telegram API robots help to add member in groups or channel more then 10k.,....

**Comment by th3unkn0n** [comment]
@VASPLab 
I think you have reached limit & also used it before maybe ~ it will be reset after 24 hour
i suggest to use 2-3 acc

@Mrnvdp07 
after all its working on telegram-api
no compeny will allow these type of hammering

i will add a extra script soon
to use multiple account at once without mannual switching

**Comment by Mrnvdp07** [comment]
Bro I think you made a tool which work are...

The tool works are which change scrap member into mutual contact list 
As there in mutual contact there is no errors comes we paste upto 50k

Can you chat me at private
I also makes a messages scrap tool which scrap all message in group 
Now I will making a bot which increases fake views in our channel  but the code has some problem
Wanna I want for help for that also.
If you want to contact at telegram 
@Raoji51 contact me bro

**Comment by Mrnvdp07** [comment]
Hey owner how you delete  my comments

**Comment by Mrnvdp07** [comment]
Hey bro 
I buy telegram thunder from your site .
Now the status seen cancelled 
But payment can't refund to me .....
Why???

**Comment by th3unkn0n** [comment]
@Mrnvdp07 i don't have any site selling anything 
#19 
i have other things to do am not spending all of my time in this

**Comment by thibaultz** [comment]
> i will add a extra script soon
> to use multiple account at once without mannual switching

I opened a post on this subject, for now even if I change my account, the message still appears ..

**Comment by Mrnvdp07** [comment]
@th3unkn0n bro your telegram thunder v6 only add 200 member in channel ....
It's very very fucking software


Although,now I have group software which is better than than bro your script
It can't scrap all member of the group 
It's exports only choosing member that's why dad member not comes 


Bro if you have any channel software for fake Orr real member for channel than gives me 😔

I want to contact with you ....
Contact me on Telegram @Raoji51

**Comment by th3unkn0n** [comment]
@Mrnvdp07 its very simple then dont use it bro, and stop opening issues here this is not comments section
