### ISSUE TITLE
Can't find groups or channels?? 

### ISSUE THREAD

**Issue by crypstone123** [th3unkn0n/TeleGram-Scraper#11]
![20200127_132631](https://user-images.githubusercontent.com/29970071/73174695-ae6acc80-4108-11ea-8f28-8bd190cfc1a2.jpg)

**Comment by th3unkn0n** [comment]
Delete token you have & login again

**Comment by crypstone123** [comment]
I deleted the phone number.session and logged in again and it's still the same thing..
My device is not rooted.. Hope it's not the cause??

**Comment by crypstone123** [comment]
Tried another number and it was successful... Still confused why the first number didn't go through..
