### ISSUE TITLE
Setup Error

### ISSUE THREAD

**Issue by POSTiGA1** [th3unkn0n/TeleGram-Scraper#12]
Hello Sir, 

I get error when run phyton3 setup.py
![Bluestacks_2020-01-29_14-52-41](https://user-images.githubusercontent.com/60429190/73353537-c8431580-42a8-11ea-8445-2dd420d89e12.png)

**Comment by POSTiGA1** [comment]
I did setup.py -u still have issue

**Comment by th3unkn0n** [comment]
$ python3 setup.py -h
			
	( --config  / -c ) setup api configration
	( --merge   / -m ) merge 2 .csv files in one 
	( --update  / -u ) update tool to latest version
	( --install / -i ) install requirements
	( --help    / -h ) show this msg

it need atlest 1 argument to run

**Comment by POSTiGA1** [comment]
Thank you , but i did the same as your tut, 
$ python3 setup.py -i requirements
$ python3 setup.py -c api
then
$ python3 scraper.py

but get error

**Comment by th3unkn0n** [comment]
No No just
$ python3 setup.py -c 
That's it only 1 arg

![Screenshot from 2020-01-31 09-23-08](https://user-images.githubusercontent.com/40244622/73511452-a7470580-440b-11ea-8d47-8d648150818b.png)
