### ISSUE TITLE
ModuleNotFoundError: No module named 'telethon'

### ISSUE THREAD

**Issue by rosaleendsouza23** [th3unkn0n/TeleGram-Scraper#20]
**showing this error. Can anyone tell me how it will be solved** 
![Screenshot_2020-02-19_20-40-59](https://user-images.githubusercontent.com/61114190/74847835-ac241880-532a-11ea-95d2-f6eb88b3c771.png)

**Comment by fathxr** [comment]
goto CMD or Powershell, hit up **python setup.py -i**
also **pip install telethon**

**Comment by rosaleendsouza23** [comment]
**i already install it pip install telethon**
i'm using kali linux its not working properly

**Comment by th3unkn0n** [comment]
It's not script issue, and use pip3 if executing script in python3
https://pypi.org/project/Telethon/

**Comment by th3unkn0n** [comment]
@rosaleendsouza23  It's not script issue, and use pip3 if executing script in python3
https://pypi.org/project/Telethon/
