### ISSUE TITLE
No module named pandas

### ISSUE THREAD

**Issue by Devp73** [th3unkn0n/TeleGram-Scraper#3]
![Screenshot_Termux_20191213-233805](https://user-images.githubusercontent.com/52715880/70821649-a1687700-1e01-11ea-94d4-95e222d04886.png)
 How to fix this ??

**Comment by th3unkn0n** [comment]
it was script problem just update it with
python3 setup.py -u
tell if it works so i can close this issue

**Comment by Devp73** [comment]
This is fixed thanks 😁

**Comment by Devp73** [comment]
@th3unkn0n Already closed my issue as it was fixed by u i checked
