### ISSUE TITLE
Again error in setup.py

### ISSUE THREAD

**Issue by cypherhack99** [th3unkn0n/TeleGram-Scraper#4]
python3 setup.py
Traceback (most recent call last):
  File "setup.py", line 86, in <module>
    if any ([sys.argv[1] == '--config', sys.argv[1] == '-c']):
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 112, in <module>
    print('\n'+gr+'['+re+'!'+gr+']'+cy+' no argument given : '+ sys.argv[1])
IndexError: list index out of range
$

**Comment by th3unkn0n** [comment]
A script error has fixed so update it by
$ python3 setup.py -u

and for how to use READ this
https://github.com/th3unkn0n/TeleGram-Scraper/blob/master/README.md#-how-to-install-and-use

**Comment by th3unkn0n** [comment]
sys.argv[] index error , use argument
