### ISSUE TITLE
Command errored out with exit status 1: python setup.py egg_info

### ISSUE THREAD

**Issue by breakimpossible** [th3unkn0n/TeleGram-Scraper#5]
I used your method in the video and when I used this command
Said that in red color
Command errored out with exit status 1: python setup.py egg_info
And when I used this command 
python3 setup.py -c
And entered the api ID & hash & phone
But didn't ask me about the code and the code not sended to telegram
And when I use this command 
python3 scrapr.py
Said cannot open file
Help me please

**Comment by th3unkn0n** [comment]
Witch module installation gave error , Can you provide any image ? Or dm me
https://t.me/Th3BoTx
