### ISSUE TITLE
Occuring flood error from telegram

### ISSUE THREAD

**Issue by cypherhack99** [th3unkn0n/TeleGram-Scraper#6]

**Comment by th3unkn0n** [comment]
ok i will remove this file

**Comment by anonymous1894** [comment]
How to add scraped members to telegram channels?

**Comment by th3unkn0n** [comment]
@anonymous1894 not added yet

**Comment by Mrnvdp07** [comment]
Bro Baar Baar flood error aa Raha h kitne multiple account opening krre jisse flood error nhi aaye

**Comment by Mrnvdp07** [comment]
Can we add more than 50 member in one time
