### ISSUE TITLE
restricted

### ISSUE THREAD

**Issue by pcdarin** [th3unkn0n/TeleGram-Scraper#9]
Why is the app restricted to sending messages to only 11 id? My member list is over 1000 people and my group is 1000 members.?
How do I edit a member.cvs?

**Comment by pcdarin** [comment]
![20200126_234029](https://user-images.githubusercontent.com/37984546/73141093-6363a180-4095-11ea-9365-3472ba03eb14.jpg)

**Comment by zLian17** [comment]
> Why is the app restricted to sending messages to only 11 id? My member list is over 1000 people and my group is 1000 members.?
> How do I edit a member.cvs?

Maybe it happen because of Tg restriction

**Comment by th3unkn0n** [comment]
Not code issue, this works on telegram API , increase time delay
